// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijmcjpefgayqjhkvjkws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqbWNqcGVmZ2F5cWpoa3Zqa3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODc2NzIsImV4cCI6MjA2NjY2MzY3Mn0.E6L6MxnFdzvqo-86NCnrX8ImuzOZwMIspDZnVP5puXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);